export const CATEGORIES = [
    { id: 'basic', text: '基底食材', icon: 'jar' },
    { id: 'basic/stock', text: '高汤' },
    { id: 'basic/sauce', text: '酱汁' },
    { id: 'basic/syrup', text: '糖浆' },
    { id: 'basic/fat', text: '油脂' },
    { id: 'basic/condiment', text: '配料' },
    { id: 'meat', text: '肉类', icon: 'steak' },
    { id: 'meat/tender', text: '嫩肉' },
    { id: 'soup', text: '汤品', icon: 'pot-food' },
    { id: 'soup/broth', text: '清汤' },
    { id: 'soup/cold-soup', text: '冷汤' },
    { id: 'aquatic', text: '水产', icon: 'fish-fins' },
    { id: 'aquatic/fish', text: '鱼类' },
    { id: 'side', text: '小吃', icon: 'french-fries' },
    { id: 'side/egg', text: '蛋类料理' },
    { id: 'side/vegetable', text: '蔬食' },
    { id: 'side/carb', text: '碳水' },
];
