export const CATEGORIES = [
    { id: 'basic', text: '基底食材' },
    { id: 'basic/stock', text: '高汤' },
    { id: 'basic/sauce', text: '酱汁' },
    { id: 'basic/syrup', text: '糖浆' },
    { id: 'basic/fat', text: '油脂' },
    { id: 'basic/condiment', text: '配料' },
    { id: 'meat', text: '肉类' },
    { id: 'meat/tender', text: '嫩肉' },
    { id: 'soup', text: '汤品' },
    { id: 'soup/broth', text: '清汤' },
    { id: 'soup/cold-soup', text: '冷汤' },
    { id: 'aquatic', text: '水产' },
    { id: 'aquatic/fish', text: '鱼类' },
    { id: 'snack', text: '小吃' },
    { id: 'snack/egg', text: '蛋类料理' },
];
